### ISSUE TITLE
Compatability with 136.0

### ISSUE THREAD

**Issue by RawToast225** [Ximi1970/systray-x#211]
**Describe the bug**
Updated to Thunderbird 136.0, and get a compatibility message

**To Reproduce**
Update to Thunderbird 136.0

**Expected behavior**
I expect it to be compatible with 136.0

**Screenshots**
![Image](https://github.com/user-attachments/assets/8163ab54-fef9-430d-9349-294b99811f14)

**Desktop (please complete the following information):**
 - OS / distribution: Arch Linux
 - Architecture x86_64
 - Desktop type / Window Manager: KDE
 - Thunderbird version and arch: Mozilla Thunderbird 136.0
 - Thunderbird package type: Arch package
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: wayland
 - Add-on version: 0.9.10 (February 7, 2025)
 - App version
 - Install type: github repository build, script installer, OBS repository: AUR `systray-x-common`
 - Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer)

**Additional context**

**Comment by tbertels** [comment]
Install https://aur.archlinux.org/packages/systray-x-git
And as always, make sure you start Thunderbird with `MOZ_ENABLE_WAYLAND=0`.

**Comment by Antiz96** [comment]
I backported the required patch set to fix compatibility with Thunderbird 136 into the Arch Linux package while waiting for a new upstream release: https://gitlab.archlinux.org/archlinux/packaging/packages/systray-x/-/commit/edc0c832e4f8afc3dabd16566bd395d5fc6da102

Should be fixed with `0.9.10-4` ;)

**Comment by Ximi1970** [comment]
Will create a new release asap but the git is indeed already working :-)

**Comment by duguyipiao** [comment]
I'm on the latest `development` branch with Manjaro xfce. I made a clean build with `make OPTIONS="DEFINES+=NO_KDE_INTEGRATION"`, but the addon still doesn't work for me.

**Comment by Ximi1970** [comment]
New release 0.9.11!
